buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20'
    }
}

plugin {
     id 'org.jetbrains.kotlin.android' version '1.7.20' apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

